a = input('Digite algo: ')
print('\n{}, é do tipo primitivo :'.format(a), type(a))
print('{}, só espaço?'.format(a), a.isspace())
print('{}, è um alfanúmerico?'.format(a), a.isalnum())
print('{}, è um númerico?'.format(a), a.isnumeric())
print('{}, è um alfabético?'.format(a), a.isalpha())
print('{}, está em maiúsculo?'.format(a), a.isupper())
print('{}. está em minúsculo?'.format(a), a.islower())
print('{}, está começando com maiúsculo(capitalizada)?'.format(a), a.istitle())